### PR TITLE
makeBinaryWrapper: Assert $1 is executable

### PR DESCRIPTION
**Pull request by doronbehar**

### CODE REVIEW

**Comment by doronbehar** [comment]
cc @bergkvist .

**Comment by bergkvist** [comment]
I like this change, but it might be better to perform this assertion inside of makeBinaryWrapper instead of makeCWrapper - because that ensures that makeCWrapper is a pure function which makes it easier to test.

I think right now this assertion would break the tests I wrote for makeCWrapper (which I notice I did after you made this PR)

**Comment by bergkvist** [comment]
Example of a test that would break, because `/path/to/executable` most likely does not exist/is not executable on the system that runs the tests:
```c

// makeCWrapper /path/to/executable

#include <unistd.h>
#include <stdlib.h>

int main(int argc, char **argv) {
    argv[0] = "/path/to/executable";
    return execv("/path/to/executable", argv);
}
```

**Comment by bergkvist** [comment]
Thanks a lot for your contribution @doronbehar! I ended up merging and moving assertExecutable from makeCWrapper to makeBinaryWrapper in an extra commit

**Pull request merged**
